#ifndef UART_TASK_UART_NOTIFY_H
#define UART_TASK_UART_NOTIFY_H

typedef enum {
    UART_ERR_OK,
    UART_ERR_FAIL,
    UART_ERR_TRANSMIT,
    UART_ERR_RECEIVE,
} uart_err_t;

typedef enum {
    UART_NOTIFY_TRANSMIT_COMPLETE = (1 << 0),
    UART_NOTIFY_RECEIVE_COMPLETE = (1 << 0),
    UART_NOTIFY_ALL = (UART_NOTIFY_TRANSMIT_COMPLETE | UART_NOTIFY_RECEIVE_COMPLETE),
} uart_notify_t;

typedef enum {
    UART_ACTION_TRANSMIT,
    UART_ACTION_RECEIVE,
    UART_ACTION_NONE,
} uart_action_t;

#endif // UART_TASK_UART_NOTIFY_H